version: "3"

services:

  nginx:
    build:
      context: .
      dockerfile: ./docker/prod/nginx/Dockerfile
    env_file: env.prod
    image: veilleur_nginx
    ports:
      - "80:80"
    links:
      - php

  php:
    build:
      context: .
      dockerfile: ./docker/prod/php/Dockerfile
    image: veilleur_php
    env_file: env.prod
    links:
      - database

  veilleur:
    build:
      context: .
      dockerfile: ./docker/prod/veilleur/Dockerfile
    env_file: env.prod
    image: veilleur_service
    links:
      - database

  database:
    image: postgres:10.3-alpine
    env_file: env.prod
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database: ~
