security:
    providers:
      hwi:
        id: veilleur.userprovider

    role_hierarchy:
      ROLE_ADMIN: ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        refresh:
            pattern:  ^/token/refresh
            stateless: true
            anonymous: true

        login:
          pattern: ^/login
          stateless: true
          anonymous: true
          oauth:
            resource_owners:
              google_auth: '/login/check-google'
            login_path: /login/check-google
            use_forward: false
            success_handler: veilleur.auth_success
            failure_handler: lexik_jwt_authentication.handler.authentication_failure
            oauth_user_provider:
              service: veilleur.userprovider

        authed_user:
          pattern: ^/(watch_links/discover)|(tags/link)|(users)/
          stateless: true
          guard:
            authenticators:
              - lexik_jwt_authentication.jwt_token_authenticator
          anonymous: false

        mainapi:
          pattern: ^/
          anonymous: true

    access_control:
      - { path: ^/(watch_links/discover)|(tags/link)|(users)/, roles: ROLE_ADMIN }
      - { path: ^/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
